// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/vektor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_proto_vektor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vektor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_vektor_proto_rawDescGZIP(), []int{0}
}

type GetStatsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PrefetchIssued   uint64                 `protobuf:"varint,1,opt,name=prefetch_issued,json=prefetchIssued,proto3" json:"prefetch_issued,omitempty"`
	PrefetchHit      uint64                 `protobuf:"varint,2,opt,name=prefetch_hit,json=prefetchHit,proto3" json:"prefetch_hit,omitempty"`
	PrefetchMiss     uint64                 `protobuf:"varint,3,opt,name=prefetch_miss,json=prefetchMiss,proto3" json:"prefetch_miss,omitempty"`
	PrefetchDropped  uint64                 `protobuf:"varint,4,opt,name=prefetch_dropped,json=prefetchDropped,proto3" json:"prefetch_dropped,omitempty"`
	TotalGetsProxied uint64                 `protobuf:"varint,5,opt,name=total_gets_proxied,json=totalGetsProxied,proto3" json:"total_gets_proxied,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_proto_vektor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vektor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_vektor_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatsResponse) GetPrefetchIssued() uint64 {
	if x != nil {
		return x.PrefetchIssued
	}
	return 0
}

func (x *GetStatsResponse) GetPrefetchHit() uint64 {
	if x != nil {
		return x.PrefetchHit
	}
	return 0
}

func (x *GetStatsResponse) GetPrefetchMiss() uint64 {
	if x != nil {
		return x.PrefetchMiss
	}
	return 0
}

func (x *GetStatsResponse) GetPrefetchDropped() uint64 {
	if x != nil {
		return x.PrefetchDropped
	}
	return 0
}

func (x *GetStatsResponse) GetTotalGetsProxied() uint64 {
	if x != nil {
		return x.TotalGetsProxied
	}
	return 0
}

type SetPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Threshold     float64                `protobuf:"fixed64,1,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Workers       int32                  `protobuf:"varint,2,opt,name=workers,proto3" json:"workers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPolicyRequest) Reset() {
	*x = SetPolicyRequest{}
	mi := &file_proto_vektor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPolicyRequest) ProtoMessage() {}

func (x *SetPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vektor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPolicyRequest.ProtoReflect.Descriptor instead.
func (*SetPolicyRequest) Descriptor() ([]byte, []int) {
	return file_proto_vektor_proto_rawDescGZIP(), []int{2}
}

func (x *SetPolicyRequest) GetThreshold() float64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *SetPolicyRequest) GetWorkers() int32 {
	if x != nil {
		return x.Workers
	}
	return 0
}

type SetPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPolicyResponse) Reset() {
	*x = SetPolicyResponse{}
	mi := &file_proto_vektor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPolicyResponse) ProtoMessage() {}

func (x *SetPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vektor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPolicyResponse.ProtoReflect.Descriptor instead.
func (*SetPolicyResponse) Descriptor() ([]byte, []int) {
	return file_proto_vektor_proto_rawDescGZIP(), []int{3}
}

func (x *SetPolicyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetModelStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelStateRequest) Reset() {
	*x = GetModelStateRequest{}
	mi := &file_proto_vektor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelStateRequest) ProtoMessage() {}

func (x *GetModelStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vektor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelStateRequest.ProtoReflect.Descriptor instead.
func (*GetModelStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_vektor_proto_rawDescGZIP(), []int{4}
}

type GetModelStateResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TrackedKeysCount uint64                 `protobuf:"varint,1,opt,name=tracked_keys_count,json=trackedKeysCount,proto3" json:"tracked_keys_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetModelStateResponse) Reset() {
	*x = GetModelStateResponse{}
	mi := &file_proto_vektor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelStateResponse) ProtoMessage() {}

func (x *GetModelStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vektor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelStateResponse.ProtoReflect.Descriptor instead.
func (*GetModelStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_vektor_proto_rawDescGZIP(), []int{5}
}

func (x *GetModelStateResponse) GetTrackedKeysCount() uint64 {
	if x != nil {
		return x.TrackedKeysCount
	}
	return 0
}

var File_proto_vektor_proto protoreflect.FileDescriptor

const file_proto_vektor_proto_rawDesc = "" +
	"\n" +
	"\x12proto/vektor.proto\x12\x06vektor\"\x11\n" +
	"\x0fGetStatsRequest\"\xdc\x01\n" +
	"\x10GetStatsResponse\x12'\n" +
	"\x0fprefetch_issued\x18\x01 \x01(\x04R\x0eprefetchIssued\x12!\n" +
	"\fprefetch_hit\x18\x02 \x01(\x04R\vprefetchHit\x12#\n" +
	"\rprefetch_miss\x18\x03 \x01(\x04R\fprefetchMiss\x12)\n" +
	"\x10prefetch_dropped\x18\x04 \x01(\x04R\x0fprefetchDropped\x12,\n" +
	"\x12total_gets_proxied\x18\x05 \x01(\x04R\x10totalGetsProxied\"J\n" +
	"\x10SetPolicyRequest\x12\x1c\n" +
	"\tthreshold\x18\x01 \x01(\x01R\tthreshold\x12\x18\n" +
	"\aworkers\x18\x02 \x01(\x05R\aworkers\"-\n" +
	"\x11SetPolicyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x16\n" +
	"\x14GetModelStateRequest\"E\n" +
	"\x15GetModelStateResponse\x12,\n" +
	"\x12tracked_keys_count\x18\x01 \x01(\x04R\x10trackedKeysCount2\xdd\x01\n" +
	"\fControlPlane\x12=\n" +
	"\bGetStats\x12\x17.vektor.GetStatsRequest\x1a\x18.vektor.GetStatsResponse\x12@\n" +
	"\tSetPolicy\x12\x18.vektor.SetPolicyRequest\x1a\x19.vektor.SetPolicyResponse\x12L\n" +
	"\rGetModelState\x12\x1c.vektor.GetModelStateRequest\x1a\x1d.vektor.GetModelStateResponseB\"Z github.com/Fnuworsu/vektor/protob\x06proto3"

var (
	file_proto_vektor_proto_rawDescOnce sync.Once
	file_proto_vektor_proto_rawDescData []byte
)

func file_proto_vektor_proto_rawDescGZIP() []byte {
	file_proto_vektor_proto_rawDescOnce.Do(func() {
		file_proto_vektor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_vektor_proto_rawDesc), len(file_proto_vektor_proto_rawDesc)))
	})
	return file_proto_vektor_proto_rawDescData
}

var file_proto_vektor_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_vektor_proto_goTypes = []any{
	(*GetStatsRequest)(nil),       // 0: vektor.GetStatsRequest
	(*GetStatsResponse)(nil),      // 1: vektor.GetStatsResponse
	(*SetPolicyRequest)(nil),      // 2: vektor.SetPolicyRequest
	(*SetPolicyResponse)(nil),     // 3: vektor.SetPolicyResponse
	(*GetModelStateRequest)(nil),  // 4: vektor.GetModelStateRequest
	(*GetModelStateResponse)(nil), // 5: vektor.GetModelStateResponse
}
var file_proto_vektor_proto_depIdxs = []int32{
	0, // 0: vektor.ControlPlane.GetStats:input_type -> vektor.GetStatsRequest
	2, // 1: vektor.ControlPlane.SetPolicy:input_type -> vektor.SetPolicyRequest
	4, // 2: vektor.ControlPlane.GetModelState:input_type -> vektor.GetModelStateRequest
	1, // 3: vektor.ControlPlane.GetStats:output_type -> vektor.GetStatsResponse
	3, // 4: vektor.ControlPlane.SetPolicy:output_type -> vektor.SetPolicyResponse
	5, // 5: vektor.ControlPlane.GetModelState:output_type -> vektor.GetModelStateResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_vektor_proto_init() }
func file_proto_vektor_proto_init() {
	if File_proto_vektor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_vektor_proto_rawDesc), len(file_proto_vektor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_vektor_proto_goTypes,
		DependencyIndexes: file_proto_vektor_proto_depIdxs,
		MessageInfos:      file_proto_vektor_proto_msgTypes,
	}.Build()
	File_proto_vektor_proto = out.File
	file_proto_vektor_proto_goTypes = nil
	file_proto_vektor_proto_depIdxs = nil
}
